


###
GET http://localhost:7007/api/vet/patients


###
GET http://localhost:7007/api/vet/patients/4

###
GET http://localhost:7007/api/vet/patients/10

###
GET http://localhost:7007/api/vet/appointments/upcoming

###
GET http://localhost:7007/api/vet/appointments/2

###
GET http://localhost:7007/api/vet/appointments/3

###
GET http://localhost:7007/api/vet/appointments/8

###
GET http://localhost:7007/api/vet/


###
GET http://localhost:7007/api/dogs

###
DELETE http://localhost:7007/api/dogs/2

###
PUT http://localhost:7007/api/dogs/3
Content-Type: application/json

{
  "id": 2,
  "name": "Enzo",
  "breed": "German Sherpherd",
  "gender": "male",
  "age": 6
}


###
POST http://localhost:7007/api/dogs/create
Content-Type: application/json

{
  "id": 3,
  "name": "Som",
  "breed": "tre",
  "gender": "female",
  "age": 4
}



### HOTEL

###
GET http://localhost:7007/api/hotels

###
GET http://localhost:7007/api/hotels/2

###
GET http://localhost:7007/api/hotels/2/rooms

###
POST http://localhost:7007/api/hotels
Content-Type: application/json

{
  "hotelName": "Hotel 3",
  "address": "address 3"
}

###
PUT http://localhost:7007/api/hotels/4
Content-Type: application/json

{
  "hotelName": "Hotel 3 changed",
  "address": "address 3"
}

###
DELETE http://localhost:7007/api/hotels/2


###
GET http://localhost:7007/api/rooms

###
GET http://localhost:7007/api/rooms/1


###
POST http://localhost:7007/api/rooms
Content-Type: application/json

{
  "number": 88,
  "price": 1500.00,
  "hotel": {
    "id": 3,
    "hotelName": "Hotel 3",
    "address": "address 3"
  }
}


###
PUT http://localhost:7007/api/rooms/4
Content-Type: application/json

{
  "number": 99,
  "price": 1500.00,
  "hotel": {
    "id": 3,
    "hotelName": "Hotel 3",
    "address": "address 3"
  }
}


###
DELETE http://localhost:7007/api/rooms/2



#########################################################################
### SECURITY ############################################################
#########################################################################

###
POST http://localhost:7007/api/auth/register
Content-Type: application/json

{
  "username": "Finn",
  "password": "1234",
  "roles": ["user"]

}


###
POST http://localhost:7007/api/auth/login
Content-Type: application/json

{
  "username": "Jonas",
  "password": "1234"

}

###
POST http://localhost:7007/api/auth/login
Content-Type: application/json

{
  "username": "Tobias",
  "password": "1234"

}


###
GET http://localhost:7007/api/protected/hotels
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaG9tYXMgSGFydG1hbm4iLCJzdWIiOiJGaW5uIiwiZXhwIjoxNzExMDM1ODc4LCJyb2xlcyI6Iix1c2VyIiwidXNlcm5hbWUiOiJGaW5uIn0.9GiLY6XEur-c9zHI3oEpk95LTmGjeFwV-tmTs9hKz7o


###
POST http://localhost:7007/api/protected/hotels
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaG9tYXMgSGFydG1hbm4iLCJzdWIiOiJGaW5uIiwiZXhwIjoxNzExMDM1ODc4LCJyb2xlcyI6Iix1c2VyIiwidXNlcm5hbWUiOiJGaW5uIn0.9GiLY6XEur-c9zHI3oEpk95LTmGjeFwV-tmTs9hKz7o
Content-Type: application/json

{
  "hotelName": "Hotel 4",
  "address": "address 4"
}

###
GET http://localhost:7007/api/protected/user_demo
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.yJpc3MiOiJUaG9tYXMgSGFydG1hbm4iLCJzdWIiOiJUb2JpYXMiLCJleHAiOjE3MTEwMzE1NDQsInJvbGVzIjoiLGFkbWluLHVzZXIiLCJ1c2VybmFtZSI6IlRvYmlhcyJ9.2Ev_qsAFxSmReEupFgWpJl3HOrmdxA5q3LSnk9jkkCc