


###
GET http://localhost:7007/api/vet/patients


###
GET http://localhost:7007/api/vet/patients/4

###
GET http://localhost:7007/api/vet/patients/10

###
GET http://localhost:7007/api/vet/appointments/upcoming

###
GET http://localhost:7007/api/vet/appointments/2

###
GET http://localhost:7007/api/vet/appointments/3

###
GET http://localhost:7007/api/vet/appointments/8

###
GET http://localhost:7007/api/vet/


###
GET http://localhost:7007/api/dogs

###
DELETE http://localhost:7007/api/dogs/2

###
PUT http://localhost:7007/api/dogs/3
Content-Type: application/json

{
  "id": 2,
  "name": "Enzo",
  "breed": "German Sherpherd",
  "gender": "male",
  "age": 6
}


###
POST http://localhost:7007/api/dogs/create
Content-Type: application/json

{
  "id": 3,
  "name": "Som",
  "breed": "tre",
  "gender": "female",
  "age": 4
}


###
GET http://localhost:7007/api/hotels

###
GET http://localhost:7007/api/hotels/2

###
GET http://localhost:7007/api/hotels/2/rooms

###
POST http://localhost:7007/api/hotels
Content-Type: application/json

{
  "hotelName": "Hotel 3",
  "address": "address 3"
}


